# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 130)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.inputValidateCPF = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputValidateCPF.setFont(font)
        self.inputValidateCPF.setObjectName("inputValidateCPF")
        self.gridLayout.addWidget(self.inputValidateCPF, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.btnValidateCPF = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnValidateCPF.setFont(font)
        self.btnValidateCPF.setObjectName("btnValidateCPF")
        self.gridLayout.addWidget(self.btnValidateCPF, 0, 3, 1, 1)
        self.btnGenerateCPF = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnGenerateCPF.setFont(font)
        self.btnGenerateCPF.setObjectName("btnGenerateCPF")
        self.gridLayout.addWidget(self.btnGenerateCPF, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.labelReturn = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelReturn.setFont(font)
        self.labelReturn.setStyleSheet("color: green;")
        self.labelReturn.setText("")
        self.labelReturn.setAlignment(QtCore.Qt.AlignCenter)
        self.labelReturn.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.labelReturn.setObjectName("labelReturn")
        self.gridLayout.addWidget(self.labelReturn, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Validate or Generate CPF"))
        self.label_2.setText(_translate("MainWindow", "Validate CPF:"))
        self.btnValidateCPF.setText(_translate("MainWindow", "VALIDATE"))
        self.btnGenerateCPF.setText(_translate("MainWindow", "GENERATE"))
        self.label.setText(_translate("MainWindow", "Generate CPF:"))
